### ISSUE TITLE
Call of overloaded function is ambiguous

### ISSUE THREAD

**Issue by dskola** [ncbi/ncbi-cxx-toolkit-public#4]
Attempting to compile with gcc 7.1.0 and getting this error:

```
XXX/ncbi-blast-2.13.0+-src/c++/include/corelib/ncbistr.hpp: In static member function ‘static std::__cxx11::string ncbi::NStr::TransformJoin(TIterator, TIterator, const ncbi::CTempString&, FTransform)’:
XXX/ncbi-blast-2.13.0+-src/c++/include/corelib/ncbistr.hpp:5498:28: error: call of overloaded ‘append(const ncbi::CTempString&)’ is ambiguous
         result.append(delim).append(fnTransform(*from));
```
 
Is this a bug or should I be using a different compiler?

**Comment by vakatov** [comment]
Hi,

Are you using this (whole C++ Toolkit) codebase -- or a BLAST one (from where exactly)?

Which build system do you use (our traditional; our CMake; or something else)?

For GCC compiler we support GCC-7.3+ (depends on the codebase too; older codebases may require earlier version).

**Comment by dskola** [comment]
Thanks for the prompt response!

> Are you using this (whole C++ Toolkit) codebase -- or a BLAST one (from where exactly)?

Whole toolkit, downloaded from https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.13.0+-src.tar.gz

> Which build system do you use (our traditional; our CMake; or something else)?

From `XXX/ncbi-blast-2.13.0+-src/c++`, run `./configure && make`

**Comment by dskola** [comment]
Will retry using this repo and the Cmake system

**Comment by vakatov** [comment]
It should work with the traditional build system, so I suspect the issue may be with the GCC version (most probably)... or maybe some other build environment.

Incidentally, what's the value of:
``grep '^CONF_CXX *=' */build/Makefile.mk``

**Comment by ucko** [comment]
Indeed, it sounds like your compiler is slightly too old to handle this code, sorry.  Do you have any newer GCC versions available?  Clang could also work; if that's an option for you, you can try pointing the build system at it by substituting ./compilers/unix/Clang.sh for ./configure .

**Comment by dskola** [comment]
Thanks, that's the conclusion I'm coming to as well. I ended up just installing from the rpm into a custom docker image and it seems to work great. Thanks!
